### ISSUE TITLE
Discord Rich Presence Working in Unity Editor but Not in Unity Android Build

### ISSUE THREAD

**Issue by asradesigning** [Lachee/discord-rpc-unity#10]
I have successfully added Discord Rich Presence to my Unity game using the 'discord-rpc-unity' plugin. However, I am encountering an issue where the feature works flawlessly within the Unity Editor but does not function as intended when building the game for Android.

**Comment by Lachee** [comment]
As far as I am aware, Discord Android does not have Rich Presence, therefore this library does not support it.
