### ISSUE TITLE
Installation error (Both OpenUPM and Manual Github)

### ISSUE THREAD

**Issue by JijaProGamer** [Lachee/discord-rpc-unity#14]
When attempting both methods I get error after installing package:

1) Asset Packages/com.lachee.discordrpc/Runtime/DiscordRPC.xml has no meta file, but it's in an immutable folder. The asset will be ignored.

2) Asset Packages/com.lachee.discordrpc/Runtime/DiscordRPC.xml has no meta file, but it's in an immutable folder. The asset will be ignored.

**Comment by Lachee** [comment]
they are warnings and dont effect anything.

**Comment by JijaProGamer** [comment]
I cannot make them go away from the error tab, do I just have to live with them?
