### ISSUE TITLE
Investigate if IL2CPP will work

### ISSUE THREAD

**Issue by Lachee** [Lachee/discord-rpc-unity#8]
Issue [243](https://github.com/discordapp/discord-rpc/issues/243) in the official library mentions Unity 2018.2 using IL2CPP for all windows builds. 

Its needs to be investigated if this will affect this library, or if it only affects callbacks from native libraries (which this one does not use). 

It also should be looked into if the latest version of Unity3D can skip the native library wrapper all together and if they have fixed the NamedPipeClient provided by C#. If it does support this, a small check can be included to only use the native library for older versions of unity.

**Comment by dylanh724** [comment]
https://forum.unity.com/threads/monopinvokecallback-in-unity.132510/
^ This thread says you _don't even need_ that attribute. I'm going to test it shortly.

**EDIT:** Nope, that didn't work ;p

**Comment by Lachee** [comment]
It does work.
